### ISSUE TITLE
marcos question: how to create object?

### ISSUE THREAD

**Issue by JeriXNet** [jasononeil/objectinit#2]
What if I want to create obj with some function, like so:

```
macro public static function init<T>( expr:ExprOf<Class<T>>, varsToSet:Array<Expr> ):ExprOf<T> {
    return doTransformation( expr, varsToSet, "init" );
}
#if macro
    static function doTransformation<T>( expr:ExprOf<Class<T>>, args:Array<Expr>, fnName:String ):ExprOf<T> {
        var lines:Array<Expr> = [];
        lines.push( macro var __obj_init_tmp = Type.createInstance($expr, []) );
        ...
```

and then use it like this:

```
var someVar = SomeClass.init(...);
```

I know there is a better way to create obj other than `Type.createInstance()` but what would that be?

**Comment by jasononeil** [comment]
Hi, sorry I lost track of this somewhere.

You would need some code like this:

``` haxe
    macro public static function instantiate<T>( expr:ExprOf<Class<T>>, varsToSet:Array<Expr> ):ExprOf<T> {
        switch Context.typeof(expr) {
            case TType(ref,params):
                var tdef = ref.get();
                var typePath = some_how_turn_tdef_into_typePath( tdef );
                // var typePath = { name:tdef.module, sub:name, pack:tdef.pack, params:null };
                var newExpr = macro new $typePath();
                return doTransformation( newExpr, varsToSet, "init" );
            case _:
                // error?
                return macro null;
        }
    }
```

But I'm not certain how what `some_how_turn_tdef_into_typePath()` needs to look like.  I'm sure if you ask for help on the mailing list someone can help.

I don't think I'll add this to ObjectInit however because it relies too much on the class having a certain kind of constructor (that is, one with no arguments).  And even though it's only a tiny bit of extra confusion, I'd rather keep it as it is now, `new SomeClass().init()` isn't that much worse than `SomeClass.init()`.
